api/urls.py
from django.urls import path

from . import views

urlpatterns = [
    path('', views.apiOverview, name='api-overview'),
    ## TASK PROJECT CATEGORY C.R.U.D
    path('task-project/', views.task_project, name='task-project'),
    path('task-project-detail/<str:pk>/', views.task_project_detail, name='task-project-detail'),
    path('task-project-create/', views.task_project_create, name='task-project-create'),
    path('task-project-update/<str:pk>/', views.task_project_update, name='task-project-update'),
    path('task-project-delete/<str:pk>/', views.task_project_delete, name='task-project-delete'),
    path('delete-all-tasks-in-category/<int:category_id>/', views.delete_all_tasks_in_category, name='delete-all-tasks-in-category'), 
    ## MAIN TASK C.R.U.D
    path('task-list/<int:category_id>/', views.task_list, name='task-list'),
    path('task-detail/<str:pk>/', views.task_detail, name='task-detail'),
    path('task-create/', views.task_create, name='task-create'),
    path('toggle-task-completion/<str:pk>/', views.toggle_task_completion, name='toggle-task-completionv'),
    path('task-update/<str:pk>/', views.task_update, name='task-update'),
    path('task-delete/<str:pk>/', views.task_delete, name='task-delete'),
    path('delete-all-tasks-in-category/<int:category_id>/', views.delete_all_tasks_in_category, name='delete-all-tasks-in-category'),
    path('category-details/<str:pk>/', views.category_details_api, name='category_details_api'),
    ## SUBTASK C.R.U.D 
    path('subtask-create/', views.subtask_create, name='subtask-create'),
    path('subtask-delete/<int:subtask_id>/', views.subtask_delete, name='subtask-delete'),
    path('update-subtask-completion-status/<int:pk>/', views.update_subtask_completion_status, name='update-subtask-completion-status'),
    path('delete-all-subtasks/<int:task_id>/', views.delete_all_subtasks, name='delete-all-subtasks'),
    path('subtask-update/<int:subtask_id>/', views.subtask_update, name='subtask-update'),
    ## JURNAL C.R.U.D
    path('jurnal-list/', views.jurnal_list, name='jurnal-list'),
    path('jurnal-detail/<str:pk>/', views.jurnal_detail, name='jurnal-detail'),
    path('jurnal-create/', views.jurnal_create, name='jurnal-create'),
    path('jurnal-update/<str:pk>/', views.jurnal_update, name='jurnal-update'),
    path('jurnal-delete/<str:pk>', views.jurnal_delete, name='jurnal-delete'),
    ## SORTABLEJS 
    path('update-task-order/<int:category_id>/', views.update_task_order, name='update-task-order'),

    path('jurnal-update-order/', views.update_jurnal_order, name='jurnal-update-order'),
    ## SEARCH BAR
    path('tasks/search/', views.search_tasks, name='search-tasks'),
    path('categories/search/', views.search_categories, name='search-categories'),
    ## CALENDER
    path('calendar/', views.calendar_events, name='calendar-events'),
    ## PROFILE
    path('update-profile/', views.update_profile, name='update-profile'),
    path('user-interests-list/', views.user_interests_list, name='user-interests-list'),
    ## NOTIFICATIONS
    path('notifications/', views.notifications, name='notifications'),
    path('notification-detail/<str:pk>/', views.notification_detail, name='notification-detail'),
    path('unread-notifications-count/', views.unread_notifications_count, name='unread-notifications-count'),
    ## EVERYTHING AI
    path('task-analysis/<int:category_id>/', views.task_analysis, name='task-analysis'),
    path('get-task-analyses/<int:category_id>/', views.get_task_analyses, name='get_task_analyses'),
    path('breakdown-task/<int:task_id>/', views.breakdown_task, name='breakdown_task'),
] 

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls')),
    
    path('', include('frontend.urls')),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

api/models.py
from django.db import models
from django.contrib.auth.models import User
from tinymce.models import HTMLField
from django.utils import timezone

# Create your models here.
class Goal(models.Model):
    # Current Situation
    current_working_on = models.TextField(blank=True)
    progress_towards_goals = models.TextField(blank=True)
    challenges = models.TextField(blank=True)

    # Desired Outcomes
    one_year_goal = models.TextField(blank=True)
    five_year_goal = models.TextField(blank=True)
    achievements_feel_successful = models.TextField(blank=True)


    def __str__(self):
        # Find the profile that has this goal
        profile = Profile.objects.filter(goal=self).first()
        if profile:
            return f"Goal Form - {self.pk} - {profile.user.username}"
        return f"Goal Form - {self.pk}"

class Interest(models.Model):
    name = models.CharField(max_length=100)

    def __str__(self):
        return self.name

class Profile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    phone_number = models.CharField(max_length=15, blank=True)
    interests = models.ManyToManyField(Interest, blank=True)  # No change needed here
    goal = models.OneToOneField('Goal', blank=True, null=True, on_delete=models.SET_NULL)

    def __str__(self):
        return self.user.username

class TaskCategory(models.Model):
    name = models.CharField(max_length=100, null=True)
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='task_categories', null=True)
    created_at = models.DateTimeField(auto_now_add=True, null=True)
    due_date = models.DateField('due date', null=True, blank=True)

    def __str__(self):
        return self.name
    
    class Meta:
        verbose_name_plural = 'taskcategories'
        ordering = ('-created_at',)

class Task(models.Model):
    category = models.ForeignKey(TaskCategory, on_delete=models.CASCADE, related_name='tasks', null=True)
    title = models.CharField(max_length=255)
    completed = models.BooleanField(default=False, blank=True)
    completion_date = models.DateField(null=True, blank=True)
    completion_time = models.TimeField(null=True, blank=True)
    description = HTMLField(blank=True, null=True)
    created_at = models.DateTimeField('due created', auto_now_add=True)
    due_date = models.DateField('due date', null=True, blank=True)
    updated_at = models.DateTimeField(auto_now=True)
    position = models.PositiveIntegerField(default=0, blank=False, null=False)
    difficulty = models.PositiveIntegerField(default=0, blank=False, null=False)  # New field for difficulty
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tasks')

    def __str__(self) -> str:
        return f'{self.title} - {self.owner} - {self.created_at} -- {self.position}'

    class Meta:
        verbose_name_plural = 'tasks'
        ordering = ('position', 'difficulty', '-created_at')

class SubTask(models.Model):
    # A reference to the parent task
    task = models.ForeignKey(Task, on_delete=models.CASCADE, related_name='subtasks')

    # Basic subtask fields
    title = models.CharField(max_length=255)
    completed = models.BooleanField(default=False)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    def __str__(self) -> str:
        return f"{self.title} - Complete: {'Yes' if self.completed else 'No'}"

    class Meta:
        verbose_name_plural = 'subtasks'
        ordering = ('created_at',)

class Jurnal(models.Model):
    owner = models.ForeignKey(User, on_delete=models.CASCADE, related_name='jurnals', null=True)
    title = models.CharField(max_length=255)
    description = HTMLField(blank=True, null=True)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    position = models.PositiveIntegerField(default=0, blank=False, null=False) 

    def __str__(self) -> str:
        return self.title

    class Meta:
        ordering = ('position', '-created_at')

class Notifications(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length=255)
    description = HTMLField(blank=True, null=True)
    NOTIFICATION_TYPE_CHOICES = (
        ('info', 'Information'),
        ('warning', 'Warning'),
        ('error', 'Error'),
        ('success', 'Success'),
    )
    notification_type = models.CharField(max_length=50, choices=NOTIFICATION_TYPE_CHOICES)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    read = models.BooleanField(default=False)

    def __str__(self):
        return f"{self.title} - {self.user.username}"

    class Meta:
        verbose_name_plural = 'notifications'
        ordering = ('-created_at',)

class TaskAnalysis(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    task = models.ForeignKey(Task, on_delete=models.CASCADE)
    analysis = models.TextField()
    created_at = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return f"Analysis for {self.task.title}"

templates/authentication/check_email.html
<h1>CHEKC EMAIL YOUR</h1>

templates/authentication/email_login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
	<meta name="description" content="Responsive Admin &amp; Dashboard Template based on Bootstrap 5">
	<meta name="author" content="AdminKit">
	<meta name="keywords" content="adminkit, bootstrap, bootstrap 5, admin, dashboard, template, responsive, css, sass, html, theme, front-end, ui kit, web">

	<link rel="preconnect" href="https://fonts.gstatic.com">
	<link rel="shortcut icon" href="img/icons/icon-48x48.png" />

	<link rel="canonical" href="https://demo.adminkit.io/pages-sign-in.html" />

	<title>Sign In | AdminKit Demo</title>

	<link href="https://fonts.googleapis.com/css2?family=Inter:wght@300;400;600&display=swap" rel="stylesheet">

	<!-- Choose your prefered color scheme -->
	<!-- <link href="css/light.css" rel="stylesheet"> -->
	<!-- <link href="css/dark.css" rel="stylesheet"> -->

	<!-- BEGIN SETTINGS -->
	<!-- Remove this after purchasing -->
	<link class="js-stylesheet" href="{% static 'css/dark.css' %}" rel="stylesheet">
	<style>
		body {
			opacity: 0;
		}
	</style>
	<!-- END SETTINGS -->
</head>
<!--
  HOW TO USE: 
  data-theme: default (default), dark, light, colored
  data-layout: fluid (default), boxed
  data-sidebar-position: left (default), right
  data-sidebar-layout: default (default), compact
-->

<body data-theme="default" data-layout="fluid" data-sidebar-position="left" data-sidebar-layout="default">
	<main class="d-flex w-100 h-100">
		<div class="container d-flex flex-column">
			<div class="row vh-100">
				<div class="col-sm-10 col-md-8 col-lg-6 col-xl-5 mx-auto d-table h-100">
					<div class="d-table-cell align-middle">

						<div class="text-center mt-4">
							<h1 class="h2">Welcome back!</h1>
							<p class="lead">
								Sign in to your account to continue
							</p>
						</div>

						<div class="card">
							<div class="card-body">
								<div class="m-sm-3">
									<div class="d-grid gap-2 mb-3">
										<a class="btn btn-google btn-lg" href="index.html"><i class="fab fa-fw fa-google"></i> Sign in with Google</a>
										<a class="btn btn-facebook btn-lg" href="index.html"><i class="fab fa-fw fa-facebook-f"></i> Sign in with Facebook</a>
										<a class="btn btn-microsoft btn-lg" href="index.html"><i class="fab fa-fw fa-microsoft"></i> Sign in with Microsoft</a>
									</div>
									<div class="row">
										<div class="col">
											<hr>
										</div>
										<div class="col-auto text-uppercase d-flex align-items-center">Or</div>
										<div class="col">
											<hr>
										</div>
									</div>
									<form method="POST">
                                        {% csrf_token %}
                                        <!-- email input -->
                                        <div class="form-outline mb-4">
                                            <input name="email" type="email" id="form1Example13" class="form-control form-control-lg" placeholder="Email" />
                                        </div>
                
                                        <!-- Password input -->
                                        <div class="form-outline mb-4">
                                            <input name="password" type="password" id="form1Example23" class="form-control form-control-lg" placeholder="password" />
                                        </div>
                                        <div class="d-grid">
                                            <button type="submit" class="btn btn-primary">Login</button>
                                        </div>
                                    </form>
								</div>
							</div>
						</div>
						<div class="text-center mb-3">
							Don't have an account? <a href="{% url 'signup' %}">Sign up</a>
                            <br>
                            Login with <a href="{% url 'login' %}">Username</a>

						</div>
					</div>
				</div>
			</div>
		</div>
	</main>

	<script src="{% static 'js/app.js' %}"></script>

</body>

</html>

templates/authentication/goal_form.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Form with Carousel and Popovers</title>
    <style>
        .popover {
            position: absolute;
            display: none;
            background-color: #333;
            color: #fff;
            padding: 10px;
            border-radius: 5px;
            width: 200px;
            z-index: 1000;
        }
        .carousel-control-prev,
        .carousel-control-next {
            z-index: 1001;
        }
    </style>
    <link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css" rel="stylesheet">
    <link href="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/css/bootstrap.min.css" rel="stylesheet">
    <link class="js-stylesheet" href="{% static 'css/dark.css' %}" rel="stylesheet">
</head>
<body>
    <div class="container" style="width: 50%;">
        <div id="carousel" class="carousel mt-3">
            <div class="carousel-inner">
                <h3><a href="{% url 'pages' %}">&#8592; Skip</a></h3>
                <form method="POST" class="my-4">

                    <div class="carousel-item active">
                        <div class="card">
                            <div class="card-body">
                                {% csrf_token %}
                                <center><h2>Current Situation</h2></center>
                                <div class="mb-3">
                                    <label for="id_current_working_on" class="form-label">
                                        Why did you choose Anton? What do you hope to achieve?
                                        <i class="align-middle me-2 fas fa-fw fa-question-circle" data-popover="I chose Anton because I want a tool that can help me stay focused and organized."></i>
                                    </label>
                                    <textarea class="form-control" id="id_current_working_on" name="current_working_on" rows="4">{{ form.current_working_on.value|default:'' }}</textarea>
                                </div>
                                <div class="mb-3">
                                    <label for="id_progress_towards_goals" class="form-label">
                                        How would you describe yourself in a few words?
                                        <i class="align-middle me-2 fas fa-fw fa-question-circle" data-popover="I am a driven professional who values continuous learning and personal growth."></i>
                                    </label>
                                    <textarea class="form-control" id="id_progress_towards_goals" name="progress_towards_goals" rows="4">{{ form.progress_towards_goals.value|default:'' }}</textarea>
                                </div>
                                <div class="mb-3">
                                    <label for="id_challenges" class="form-label">
                                        What personal or professional challenges are you currently facing?
                                        <i class="align-middle me-2 fas fa-fw fa-question-circle" data-popover="I struggle with procrastination and often find it hard to stick to my goals."></i>
                                    </label>
                                    <textarea class="form-control" id="id_challenges" name="challenges" rows="4">{{ form.challenges.value|default:'' }}</textarea>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div class="carousel-item">
                        <div class="card">
                            <div class="card-body">
                                <center><h2>Desired Outcomes</h2></center>
                                <div class="mb-3">
                                    <label for="id_one_year_goal" class="form-label">
                                        What are your top three personal development goals?
                                        <i class="align-middle me-2 fas fa-fw fa-question-circle" data-popover="I want to improve my time management, develop a positive mindset, and learn a new skill."></i>
                                    </label>
                                    <textarea class="form-control" id="id_one_year_goal" name="one_year_goal" rows="4">{{ form.one_year_goal.value|default:'' }}</textarea>
                                </div>
                                <div class="mb-3">
                                    <label for="id_five_year_goal" class="form-label">
                                        How do you prefer to receive feedback or support?
                                        <i class="align-middle me-2 fas fa-fw fa-question-circle" data-popover="I prefer receiving constructive feedback through actionable suggestions and positive reinforcement."></i>
                                    </label>
                                    <textarea class="form-control" id="id_five_year_goal" name="five_year_goal" rows="4">{{ form.five_year_goal.value|default:'' }}</textarea>
                                </div>
                                <div class="mb-3">
                                    <label for="id_achievements_feel_successful" class="form-label">
                                        What areas do you feel you need the most improvement in?
                                        <i class="align-middle me-2 fas fa-fw fa-question-circle" data-popover="I need to work on my confidence and being more assertive in social situations."></i>
                                    </label>
                                    <textarea class="form-control" id="id_achievements_feel_successful" name="achievements_feel_successful" rows="4">{{ form.achievements_feel_successful.value|default:'' }}</textarea>
                                </div>
                            </div>
                            <button type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </div>

                    
            </form>
                
            </div>
            <div class="carousel-controls">
                <div class="row">
                    <div class="col">
                        <button class="btn btn-outline-primary form-control" id="prevBtn">Previous</button>
                    </div>
                    <div class="col">
                        <button class="btn btn-outline-primary form-control" id="nextBtn">Next</button>
                    </div>

                </div>
            </div>
           
        </div>
    </div>
    
    <div id="popover" class="popover"></div>
    
    <script>
        document.addEventListener('DOMContentLoaded', function() {
            var popover = document.getElementById('popover');
            var triggers = document.querySelectorAll('[data-popover]');
            var carousel = document.getElementById('carousel');
            var items = carousel.querySelectorAll('.carousel-item');
            var currentIndex = 0;
    
            function showItem(index) {
                items[currentIndex].classList.remove('active');
                items[index].classList.add('active');
                currentIndex = index;
                updateButtons();
            }
    
            function updateButtons() {
                var prevBtn = document.getElementById('prevBtn');
                var nextBtn = document.getElementById('nextBtn');
    
                if (currentIndex === 0) {
                    prevBtn.style.display = 'none';
                } else {
                    prevBtn.style.display = 'block';
                }
    
                if (currentIndex === items.length - 1) {
                    nextBtn.style.display = 'none';
                } else {
                    nextBtn.style.display = 'block';
                }
            }
    
            document.getElementById('prevBtn').addEventListener('click', function() {
                var nextIndex = (currentIndex - 1 + items.length) % items.length;
                showItem(nextIndex);
            });
    
            document.getElementById('nextBtn').addEventListener('click', function() {
                var nextIndex = (currentIndex + 1) % items.length;
                showItem(nextIndex);
            });
    
            triggers.forEach(function(trigger) {
                trigger.addEventListener('click', function(event) {
                    event.preventDefault(); // Prevent default behavior
                    var content = this.getAttribute('data-popover');
                    popover.innerHTML = content;
                    var rect = this.getBoundingClientRect();
                    popover.style.top = (rect.bottom + window.scrollY + 10) + 'px';
                    popover.style.left = (rect.left + window.scrollX + (rect.width / 2) - (popover.offsetWidth / 2)) + 'px';
                    popover.style.display = (popover.style.display === 'block') ? 'none' : 'block';
                });
            });
    
            document.addEventListener('click', function(event) {
                if (!popover.contains(event.target) && !event.target.matches('[data-popover]')) {
                    popover.style.display = 'none';
                }
            });
    
            // Initial call to update buttons
            updateButtons();
        });
    </script>
    
    

<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.2/dist/umd/popper.min.js"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/5.1.3/js/bootstrap.min.js"></script>

</body>
</html>

templates/authentication/interests.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>

    <link rel="preconnect" href="https://fonts.gstatic.com">
	<link rel="shortcut icon" href="{% static 'img/icons/icon-48x48.png' %}" />

	<link class="js-stylesheet" href="{% static 'css/dark.css' %}" rel="stylesheet">
</head>
<body>
    <style>
        .checkbox-group {
            display: flex;
            flex-wrap: wrap; /* Allows the cards to wrap to the next line if necessary */
            background-color: #222E3C;
            padding: 12px;
            border-top-left-radius: 15px;  /* Bottom left corner */
            border-top-right-radius: 15px; /* Bottom right corner */
        
        }
        
        .checkmark-container {
            margin-bottom: 10px; /* Adds space between each checkbox item */
        }
        
        .badge {
            background-color: #19222c;
            padding: 8px;
            color: #fff; /* Ensure text is readable */
            display: flex;
            align-items: center; /* Aligns the checkbox and label vertically centered */
            margin-right: 8px; /* Adds space between badge pills */
            margin-bottom: 8px; /* Adds space between rows of badges */
        }
        
        .checkmark {
            width: 15px;
            height: 15px;
            -webkit-appearance: none;
            -moz-appearance: none;
            appearance: none;
            border: 2px solid #39B54A;
            border-radius: 50%;
            outline: none;
            cursor: pointer;
            position: relative;
            transition: background-color 0.3s, transform 0.3s;
            margin-right: 8px; /* Adds space between checkbox and label */
        }
        
        .checkmark:checked {
            background-color: #39B54A;
            transform: scale(1.2);
        }
        
        .checkmark:checked::after {
            content: '';
            position: absolute;
            left: 4px;
            top: 1px;
            width: 4px;
            height: 7px;
            border: solid #fff;
            border-width: 0 2px 2px 0;
            transform: rotate(45deg);
        }
        .typing-effect {
            font-size: 24px;
            white-space: nowrap;
            overflow: hidden;
            border-right: 3px solid;
            animation: blink-caret 0.75s step-end infinite;
        }

        @keyframes blink-caret {
            from, to {
                border-color: transparent;
            }
            50% {
                border-color: black;
            }
        }
        </style>
        <div class="container" style="margin-top: 1.5rem;">
            <center>
                <h3 class="typing-effect" id="typing-effect"></h3>
                <p>Select the mindset you want to cultivate and connect with others on the same journey!</p>
            </center>
            <form method="post">
                {% csrf_token %}
                <div class="checkbox-group">
                    {% for interest in form.interests %}
                        <div class="checkmark-container">
                            <span class="badge rounded-pill">
                                {{ interest.tag|safe }}
                                {{ interest.choice_label }}
                            </span>
                        </div>
                    {% endfor %}
                </div>
                <button class="btn btn-primary form-control" type="submit">Save</button>
            </form>
        </div>

    <script>
        document.addEventListener('DOMContentLoaded', function () {
            const text = "NeoAnton";
            let index = 0;
            const typingElement = document.getElementById('typing-effect');

            function type() {
                if (index < text.length) {
                    typingElement.innerHTML += text.charAt(index);
                    index++;
                    setTimeout(type, 100); // Adjust the speed by changing the timeout value
                }
            }

            type();
        });
    </script>
</body>
</html>

templates/authentication/profile.html
{% extends 'base.html' %}
{% load static %}

{% block content %}
<div class="container-fluid p-0 d-flex justify-content-center">
    <div>
        <h1 class="h3 mb-3 text-center">Profile</h1>

        <div class="row justify-content-center">
            <div class="col">
                <div class="card mb-3">
                    <div class="card-body text-center">
                        <img src="{% static 'img/icons/user (1).png' %}" alt="Christina Mason"
                            class="img-fluid rounded-circle mb-2" width="128" height="128">
                        <h5 class="card-title mb-0">username </h5>
                        <div class="text-muted mb-2">first and last name</div>
                    </div>
                    <hr class="my-0">
                    <div class="card-body intrests">
                        <h5 class="h6 card-title">intrests</h5>
                        <!-- This is where the a tags are going to goof interest -->
                    </div>
                    <hr class="my-0">
                    <div class="card-body">
                        <h5 class="h6 card-title">Elsewhere</h5>
                        <ul class="list-unstyled mb-0 d-flex flex-wrap">
                            <li class="mb-1 me-3"><span class="fas fa-globe fa-fw me-1"></span> <a
                                    href="#">staciehall.co</a></li>
                            <li class="mb-1 me-3"><span class="fab fa-twitter fa-fw me-1"></span> <a
                                    href="#">Twitter</a></li>
                            <li class="mb-1 me-3"><span class="fab fa-facebook fa-fw me-1"></span> <a
                                    href="#">Facebook</a></li>
                            <li class="mb-1 me-3"><span class="fab fa-instagram fa-fw me-1"></span> <a
                                    href="#">Instagram</a></li>
                            <li class="mb-1"><span class="fab fa-linkedin fa-fw me-1"></span> <a href="#">LinkedIn</a>
                            </li>
                        </ul>
                    </div>

                </div>
            </div>
        </div>
    </div>
</div>

<script>
document.addEventListener('DOMContentLoaded', () => {
    fetch('http://127.0.0.1:7000/api/user-interests-list/', {
        headers: {
            'Content-Type': 'application/json'
        }
    })
    .then(response => 
        response.ok ? response.json() : Promise.reject(`HTTP error! status: ${response.status}`)
    )
    .then(data => {
        const cardBody = document.querySelector('.intrests');

        // Update username
        const usernameElement = document.querySelector('.card-title.mb-0');
        usernameElement.textContent = data.user.username;

        // Update first and last name
        const nameElement = document.querySelector('.text-muted.mb-2');
        nameElement.textContent = `${data.user.first_name} ${data.user.last_name}`;

        // Clear any existing badges if necessary
        cardBody.querySelectorAll('.badge').forEach(badge => badge.remove());

        // Display interests
        data.interests.forEach(interest => {
            const badge = document.createElement('a');
            badge.href = '#';
            badge.className = 'badge bg-primary me-1 my-1';
            badge.textContent = interest.name;

            cardBody.appendChild(badge);
        });
    })
    .catch(error => {
        console.error('Error fetching interests:', error);
    });
});





</script>

{% endblock %}